trigger:
- main

variables:
  dockerRegistryServiceConnection: 'c5c4b489-59df-4f46-854e-3baf27220071'
  imageRepository: 'myrecipebook'
  containerRegistry: 'apiprojectmyrecipebook.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
      vmImage: 'ubuntu-latest'

steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(tag)